services:
  backend:
    build: 
      context: .
      dockerfile: ./time_manager/Dockerfile
    container_name: time_manager_backend
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: prod
      PHX_SERVER: "true"
      DATABASE_URL: ecto://postgres:postgres@db/time_manager_dev
      SECRET_KEY_BASE: "ycynbOktJ7zgIZrpJPGX2R9vLz9AcM2gKhxh6mjHPo8/wbIDU/Cd4A2ACvIXP7QI"
      PHX_HOST: localhost
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time_manager_dev
    ports:
      - "5432:5432"
    networks:
      - app_network

  frontend:
    build:
      context: ./client
    container_name: time_manager_frontend
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
