# backend/config/dev.exs
import Config

# Debug: Print environment variables
dburl = System.get_env("DATABASE_URL")
IO.puts "DATABASE_URL: #{dburl}"
IO.puts "DB_NAME: #{System.get_env("DB_NAME")}"

# Configure your database
config :time_manager, TimeManager.Repo,
  username: System.get_env("DB_USER"),
  password: System.get_env("DB_PASS"),
  hostname: System.get_env("DB_HOST"),
  database: System.get_env("DB_NAME"),
  port: String.to_integer(System.get_env("DB_PORT") || "5432"),
  ssl: true,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")

# Print the final configuration
repo_config = Application.get_env(:time_manager, TimeManager.Repo)
IO.puts "Final Repo Config: #{inspect(repo_config)}"


# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :time_manager, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
