# backend/config/dev.exs
import Config

# Debug: Print environment variables
dburl = System.get_env("DATABASE_URL")
IO.puts "DATABASE_URL: #{dburl}"
IO.puts "DB_NAME: #{System.get_env("DB_NAME")}"

# Configure your database
config :time_manager, TimeManager.Repo,
  username: System.get_env("DB_USER"),
  password: System.get_env("DB_PASS"),
  hostname: System.get_env("DB_HOST"),
  database: System.get_env("DB_NAME"),
  port: String.to_integer(System.get_env("DB_PORT") || "5432"),
  ssl: true,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")

# Print the final configuration
repo_config = Application.get_env(:time_manager, TimeManager.Repo)
IO.puts "Final Repo Config: #{inspect(repo_config)}"

# For development, we disable any cache and enable
# debugging and code reloading.
config :time_manager, TimeManagerWeb.Endpoint,
  # Change IP binding to allow external connections
  http: [
    ip: {0, 0, 0, 0},
    port: String.to_integer(System.get_env("PORT") || "4000")
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  server: true,  # Make sure the server starts
  secret_key_base: "VYOh1HDmw0ng3paROJ1bPCYi/2BatcDuyt3G1bJcySsuxzLn9TSqrN303REqKqUo",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:time_manager, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:time_manager, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :time_manager, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
